/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthedAttendanceRouteImport } from './routes/_authed/attendance'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedDepartmentsRouteImport } from './routes/_authed/departments'
import { Route as AuthedLeaveRouteImport } from './routes/_authed/leave'
import { Route as AuthedPayrollRouteImport } from './routes/_authed/payroll'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedEmployeesIndexRouteImport } from './routes/_authed/employees/index'
import { Route as AuthedEmployeesEmployeeIdRouteImport } from './routes/_authed/employees/$employeeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAttendanceRoute = AuthedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDepartmentsRoute = AuthedDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLeaveRoute = AuthedLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPayrollRoute = AuthedPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEmployeesIndexRoute = AuthedEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEmployeesEmployeeIdRoute =
  AuthedEmployeesEmployeeIdRouteImport.update({
    id: '/employees/$employeeId',
    path: '/employees/$employeeId',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/attendance': typeof AuthedAttendanceRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/departments': typeof AuthedDepartmentsRoute
  '/leave': typeof AuthedLeaveRoute
  '/payroll': typeof AuthedPayrollRoute
  '/settings': typeof AuthedSettingsRoute
  '/employees/$employeeId': typeof AuthedEmployeesEmployeeIdRoute
  '/employees/': typeof AuthedEmployeesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/attendance': typeof AuthedAttendanceRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/departments': typeof AuthedDepartmentsRoute
  '/leave': typeof AuthedLeaveRoute
  '/payroll': typeof AuthedPayrollRoute
  '/settings': typeof AuthedSettingsRoute
  '/employees/$employeeId': typeof AuthedEmployeesEmployeeIdRoute
  '/employees': typeof AuthedEmployeesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authed/attendance': typeof AuthedAttendanceRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/departments': typeof AuthedDepartmentsRoute
  '/_authed/leave': typeof AuthedLeaveRoute
  '/_authed/payroll': typeof AuthedPayrollRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/employees/$employeeId': typeof AuthedEmployeesEmployeeIdRoute
  '/_authed/employees/': typeof AuthedEmployeesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/attendance'
    | '/dashboard'
    | '/departments'
    | '/leave'
    | '/payroll'
    | '/settings'
    | '/employees/$employeeId'
    | '/employees/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/attendance'
    | '/dashboard'
    | '/departments'
    | '/leave'
    | '/payroll'
    | '/settings'
    | '/employees/$employeeId'
    | '/employees'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/_authed/attendance'
    | '/_authed/dashboard'
    | '/_authed/departments'
    | '/_authed/leave'
    | '/_authed/payroll'
    | '/_authed/settings'
    | '/_authed/employees/$employeeId'
    | '/_authed/employees/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/attendance': {
      id: '/_authed/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthedAttendanceRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/departments': {
      id: '/_authed/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AuthedDepartmentsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/leave': {
      id: '/_authed/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof AuthedLeaveRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/payroll': {
      id: '/_authed/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AuthedPayrollRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/employees/': {
      id: '/_authed/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof AuthedEmployeesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/employees/$employeeId': {
      id: '/_authed/employees/$employeeId'
      path: '/employees/$employeeId'
      fullPath: '/employees/$employeeId'
      preLoaderRoute: typeof AuthedEmployeesEmployeeIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAttendanceRoute: typeof AuthedAttendanceRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedDepartmentsRoute: typeof AuthedDepartmentsRoute
  AuthedLeaveRoute: typeof AuthedLeaveRoute
  AuthedPayrollRoute: typeof AuthedPayrollRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedEmployeesEmployeeIdRoute: typeof AuthedEmployeesEmployeeIdRoute
  AuthedEmployeesIndexRoute: typeof AuthedEmployeesIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAttendanceRoute: AuthedAttendanceRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedDepartmentsRoute: AuthedDepartmentsRoute,
  AuthedLeaveRoute: AuthedLeaveRoute,
  AuthedPayrollRoute: AuthedPayrollRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedEmployeesEmployeeIdRoute: AuthedEmployeesEmployeeIdRoute,
  AuthedEmployeesIndexRoute: AuthedEmployeesIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
